name: khazana_mutual_funds
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7
  dartz: ^0.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3+1
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  rate_my_app: ^2.3.1
  device_info_plus: ^11.3.0
  get_it: ^8.0.3
  vibration: ^3.1.2
  shared_preferences: ^2.5.2
  flex_color_scheme: ^8.2.0
  url_launcher: ^6.3.1
  flutter_spinkit: ^5.2.1
  super_tooltip: ^2.0.9
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  go_router: ^15.1.2
  supabase_flutter: ^2.9.0
  flutter_otp_text_field: ^1.5.1+1

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.svg
    - assets/images/
    - assets/images/auth_background.png
